const D=window.GAME_DATA,KEY='sql-master-ver4-full';let S=JSON.parse(localStorage.getItem(KEY)||'null')||{xp:0,hp:5,done:{},boss:{},daily:{},ach:[],lastDay:'',streak:1};let U=null,si=0,pick=null;const app=document.getElementById('app');
function save(){localStorage.setItem(KEY,JSON.stringify(S));hud();achievements()}
function hud(){xp.textContent=S.xp;hp.textContent=S.hp;lv.textContent=level()}
function level(){return Math.min(100,1+Math.floor(S.xp/100))}
function title(){let l=level();return l>=100?'SQLマスター':l>=75?'データ勇者':l>=50?'分析賢者':l>=40?'分析士':l>=30?'JOIN使い':l>=20?'抽出マスター':l>=10?'集計使い':l>=5?'データ探索者':'SQL見習い'}
function norm(s){return s.toLowerCase().replace(/;/g,'').replace(/\s+/g,' ').replace(/\s*,\s*/g,',').replace(/\s*\(\s*/g,'(').replace(/\s*\)\s*/g,')').trim()}
function done(id){return S.done[id]||0}
function tierComplete(t){return D.units.filter(u=>u.tier===t).every(u=>done(u.id)>=5)}
function tierOpen(t){if(t==='初級')return true;if(t==='中級')return S.xp>=1000&&S.boss.beginner;if(t==='上級')return S.xp>=3000&&S.boss.intermediate;return false}
function unitOpen(u){if(!tierOpen(u.tier))return false;let arr=D.units.filter(x=>x.tier===u.tier),i=arr.findIndex(x=>x.id===u.id);return i===0||done(arr[i-1].id)>=5}
function go(v){({home,world,daily,skills,profile}[v]||home)()}
function home(){app.innerHTML=`<section class="hero"><span class="tag">VER4 RPG EDITION</span><h1>SQLを学び、<em>世界を解放</em>せよ。</h1><p>初級・中級・上級の30ユニット。毎日のクエスト、3体のボス、スキルツリーと実績を攻略してSQLマスターを目指します。</p><button class="btn primary" onclick="world()">冒険を始める</button></section><h2>冒険者ステータス</h2><div class="grid"><div class="card"><div class="big">Lv.${level()}</div><b>${title()}</b></div><div class="card"><div class="big">${S.xp} XP</div><b>次のレベルまで ${100-S.xp%100} XP</b><div class="progress"><span style="width:${S.xp%100}%"></span></div></div><div class="card"><div class="big">${Object.values(S.done).filter(x=>x>=5).length}/30</div><b>修了ユニット</b></div></div><section class="card daily"><h2>☀️ 今日のデイリー</h2><p>毎日1問で学習習慣をつくろう。</p><button class="btn primary" onclick="daily()">挑戦する</button></section>`}
function world(){app.innerHTML=`<h1>ワールドマップ</h1><p class="muted">中級は初級ボス撃破＋1000XP、上級は中級ボス撃破＋3000XPで解放されます。</p>${['初級','中級','上級'].map(t=>tierHtml(t)).join('')}`}
function tierHtml(t){let open=tierOpen(t),arr=D.units.filter(u=>u.tier===t),boss=D.bosses.find(b=>b.tier===t);return `<section class="tier"><div class="tierHead"><h2>${t==='初級'?'🌱':t==='中級'?'⚔️':'👑'} ${t}編</h2><span>${open?'解放済み':'🔒 未解放'}</span></div><div class="units">${arr.map(u=>`<article class="card unit ${unitOpen(u)?'':'locked'}" onclick="${unitOpen(u)?`start(${u.id})`:''}"><span class="tag">UNIT ${u.id}</span><h3>${u.title}</h3><p class="muted">${u.topic}</p><div class="progress"><span style="width:${done(u.id)*20}%"></span></div></article>`).join('')}</div>${bossCard(boss,open&&tierComplete(t))}</section>`}
function bossCard(b,avail){let clear=S.boss[b.id];return `<article class="card boss"><h3>👹 ${b.name}</h3><p>${b.prompt}</p><p class="muted">必須スキル：${b.requires.join(' / ')}</p><button class="btn ${avail&&!clear?'primary':''}" ${avail&&!clear?'': 'disabled'} onclick="bossFight('${b.id}')">${clear?'撃破済み':avail?'ボスに挑む':'全UNITクリアで解放'}</button></article>`}
function start(id){U=D.units.find(u=>u.id===id);si=Math.min(done(id),4);renderStep()}
function renderStep(){pick=null;let st=U.steps[si];app.innerHTML=`<div class="lessonTop"><span class="tag">${U.tier} UNIT ${U.id}</span><div><h1>${U.title}</h1><p class="muted">${U.topic}</p></div></div><div class="stepbar">${[0,1,2,3,4].map(i=>`<i class="${i<=si?'on':''}"></i>`).join('')}</div><section class="card"><h2>${st.title}</h2>${stepBody(st)}<div id="feed"></div><div class="actions"><button class="btn" onclick="world()">マップ</button>${st.type==='lesson'?'<button class="btn primary" onclick="pass()">理解した</button>':st.type==='choice'||st.type==='predict'?'<button class="btn primary" onclick="checkChoice()">答え合わせ</button>':st.type==='fill'?'<button class="btn primary" onclick="checkFill()">答え合わせ</button>':'<button class="btn primary" onclick="checkWrite()">判定する</button>'}</div></section>`}
function stepBody(st){if(st.type==='lesson')return `<p>${st.prompt}</p><pre>${U.answer}</pre><p class="muted">${U.hint}</p>`;if(st.type==='choice'||st.type==='predict')return `${st.type==='predict'?`<pre>${st.prompt}</pre>`:`<p>${st.prompt}</p>`}<div class="options">${st.options.map((o,i)=>`<button class="option" onclick="choose(${i},this)">${o}</button>`).join('')}</div>`;if(st.type==='fill')return `<p>${st.prompt}</p><input id="fill" class="editor" style="min-height:60px" placeholder="キーワードを入力">`;return `<p>${st.prompt}</p><textarea id="sql" class="editor" placeholder="ここにSQLを入力"></textarea><p class="muted">ヒント：${st.hint}</p>`}
function choose(i,e){pick=i;document.querySelectorAll('.option').forEach(x=>x.classList.remove('pick'));e.classList.add('pick')}
function feedback(ok,msg){feed.innerHTML=`<div class="feedback ${ok?'ok':'ng'}">${ok?'🎉 正解':'💡 再挑戦'}<br>${msg}</div>${ok?'<button class="btn primary" onclick="next()">次へ</button>':''}`;if(!ok){S.hp=Math.max(0,S.hp-1);save()}}
function award(){if(done(U.id)<=si){S.done[U.id]=si+1;S.xp+=U.steps[si].xp;if(si===4)S.xp+=50;save()}}
function pass(){award();next()}
function checkChoice(){if(pick===null)return feedback(false,'選択肢を選んでください。');let st=U.steps[si],ok=pick===st.correct;feedback(ok,ok?'理解できています。':'解説に戻って確認しましょう。');if(ok)award()}
function checkFill(){let st=U.steps[si],ok=norm(fill.value)===norm(st.correct);feedback(ok,ok?'キーワード正解です。':U.hint);if(ok)award()}
function checkWrite(){let v=sql.value;if(!v.trim())return feedback(false,'SQLを入力してください。');let ok=norm(v)===norm(U.steps[si].answer);feedback(ok,ok?`解答例：${U.answer}`:U.hint);if(ok)award()}
function next(){if(si<4){si++;renderStep()}else{app.innerHTML=`<section class="card" style="text-align:center"><div style="font-size:5rem">🏆</div><h1>UNIT ${U.id} クリア！</h1><p>完全クリアボーナス +50 XP</p><button class="btn primary" onclick="world()">マップへ</button></section>`}}
function bossFight(id){let b=D.bosses.find(x=>x.id===id);app.innerHTML=`<section class="card boss"><span class="tag">BOSS BATTLE</span><h1>👹 ${b.name}</h1><p>${b.prompt}</p><textarea id="bossSql" class="editor" placeholder="ボスを倒すSQLを書く"></textarea><div id="bossFeed"></div><button class="btn primary" onclick="checkBoss('${id}')">攻撃する</button></section>`}
function checkBoss(id){let b=D.bosses.find(x=>x.id===id),ok=norm(bossSql.value)===norm(b.answer);bossFeed.innerHTML=`<div class="feedback ${ok?'ok':'ng'}">${ok?'⚔️ BOSS CLEAR! +'+b.reward+' XP':'攻撃失敗。必要スキル：'+b.requires.join(' / ')}</div>`;if(ok&&!S.boss[id]){S.boss[id]=true;S.xp+=b.reward;save();bossFeed.innerHTML+=`<button class="btn primary" onclick="world()">次の世界へ</button>`}else if(!ok){S.hp=Math.max(0,S.hp-1);save()}}
function dayKey(){return new Date().toISOString().slice(0,10)}function dailyItem(){let n=Math.floor(Date.now()/86400000)%D.dailies.length;return D.dailies[n]}
function daily(){let q=dailyItem(),doneToday=S.daily[dayKey()];app.innerHTML=`<h1>☀️ デイリークエスト</h1><section class="card daily"><span class="tag">${q.tier}・${q.xp} XP</span><h2>${q.prompt}</h2>${doneToday?'<div class="feedback ok">本日はクリア済みです。</div>':`<textarea id="dailySql" class="editor" placeholder="SQLを入力"></textarea><div id="dailyFeed"></div><button class="btn primary" onclick="checkDaily()">判定する</button>`}</section>`}
function checkDaily(){let q=dailyItem(),ok=norm(dailySql.value)===norm(q.answer);dailyFeed.innerHTML=`<div class="feedback ${ok?'ok':'ng'}">${ok?'デイリークリア！ +'+q.xp+' XP':'もう一度挑戦しよう'}</div>`;if(ok&&!S.daily[dayKey()]){S.daily[dayKey()]=true;S.xp+=q.xp;S.hp=Math.min(5,S.hp+1);save()}else if(!ok){S.hp=Math.max(0,S.hp-1);save()}}
function skills(){app.innerHTML=`<h1>🌳 スキルツリー</h1><p class="muted">UNIT完全クリアでスキルの書を獲得します。</p><div class="skillTree">${D.units.map(u=>`<div class="card skill ${done(u.id)>=5?'':'off'}"><div style="font-size:2rem">${done(u.id)>=5?'📖':'🔒'}</div><b>${u.title}</b><small class="muted">${done(u.id)>=5?'習得済み':'未習得'}</small></div>`).join('')}</div>`}
function achievements(){let tests=[['first',Object.keys(S.done).length>0],['beginner',S.boss.beginner],['intermediate',S.boss.intermediate],['advanced',S.boss.advanced],['xp1000',S.xp>=1000],['xp3000',S.xp>=3000],['master',level()>=100]];tests.forEach(([k,v])=>{if(v&&!S.ach.includes(k))S.ach.push(k)});localStorage.setItem(KEY,JSON.stringify(S))}
function profile(){let names={first:'🌱 はじめの一歩',beginner:'🥉 初級制覇',intermediate:'🥈 中級制覇',advanced:'🥇 上級制覇',xp1000:'⭐ 1000 XP',xp3000:'💎 3000 XP',master:'👑 SQLマスター'};app.innerHTML=`<h1>🏆 プロフィール・実績</h1><div class="grid"><div class="card"><div class="big">Lv.${level()}</div><b>${title()}</b></div><div class="card"><div class="big">${S.xp}</div><b>総XP</b></div><div class="card"><div class="big">${S.ach.length}</div><b>実績</b></div></div><section class="card"><h2>獲得実績</h2>${S.ach.length?S.ach.map(k=>`<span class="badge">${names[k]}</span>`).join(''):'<p class="muted">まだ実績はありません。</p>'}</section><button class="btn danger" onclick="if(confirm('全進捗を削除しますか？')){localStorage.removeItem(KEY);location.reload()}">進捗をリセット</button>`}
hud();home();